version: '3.3'

services:
    pytorch_service:
        image: yolov5_image
        container_name: yolov5
        build: 
          context: ..
          dockerfile: .docker/Dockerfile
        volumes:
            - ..:/root/yolov5
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=3
        tty: true
        # ports: 
        #   - "3000:3000"
        stdin_open: true
        command: ["bash"]